export const banks = [
    { bankNumber: "", bankName: "--Selecione--" },
    { bankNumber: "197", bankName: "Stone Pagamentos" },
    { bankNumber: "748", bankName: "Banco Cooperativo Sicredi S.A." },
    { bankNumber: "117", bankName: "Advanced Cc Ltda" },
    { bankNumber: "007", bankName: "Banco Inter" },
    { bankNumber: "290", bankName: "PagBank" },
    { bankNumber: "260", bankName: "Nubank" },
    { bankNumber: "340", bankName: "Superdigital" },
    { bankNumber: "121", bankName: "Banco Agibank S.A." },
    { bankNumber: "237", bankName: "Next" },
    { bankNumber: "212", bankName: "Banco Original" },
    { bankNumber: "323", bankName: "Mercado Pago" },
    { bankNumber: "380", bankName: "PicPay" },
    { bankNumber: "033", bankName: "Banco SANTANDER" },
    { bankNumber: "237", bankName: "Banco Bradesco S.A." },
    { bankNumber: "208", bankName: "Banco BTG Pactual S.A." },
    { bankNumber: "001", bankName: "Banco do Brasil S.A." },
    { bankNumber: "341", bankName: "Banco Itaú" },
    { bankNumber: "479", bankName: "Banco ItauBank S.A." },
    { bankNumber: "029", bankName: "Banco Itaú Consignado S.A." },
    { bankNumber: "336", bankName: "Banco C6 S.A – C6 Bank" },
    { bankNumber: "473", bankName: "Banco Caixa Geral – Brasil S.A." },
    { bankNumber: "104", bankName: "Banco Caixa Econômica Federal" },
    { bankNumber: "745", bankName: "Banco Citibank S.A." },
]